drop table IF EXISTS ACT_CY_CONN_CONFIG;
drop table IF EXISTS ACT_CY_CONFIG;
drop table IF EXISTS ACT_CY_LINK;
drop table IF EXISTS ACT_CY_PEOPLE_LINK;
drop table IF EXISTS ACT_CY_TAG;
drop table IF EXISTS ACT_CY_COMMENT;
drop table IF EXISTS ACT_CY_V_FOLDER;
drop table IF EXISTS ACT_CY_PROCESS_SOLUTION;
