drop index IF EXISTS ACT_IDX_HI_PRO_INST_END;
drop index IF EXISTS ACT_IDX_HI_PRO_I_BUSKEY;
drop index IF EXISTS ACT_IDX_HI_ACT_INST_START;
drop index IF EXISTS ACT_IDX_HI_ACT_INST_END;
drop index IF EXISTS ACT_IDX_HI_DETAIL_PROC_INST;
drop index IF EXISTS ACT_IDX_HI_DETAIL_ACT_INST;
drop index IF EXISTS ACT_IDX_HI_DETAIL_TIME;
drop index IF EXISTS ACT_IDX_HI_DETAIL_NAME;

drop table IF EXISTS ACT_HI_PROCINST;
drop table IF EXISTS ACT_HI_ACTINST;
drop table IF EXISTS ACT_HI_TASKINST;
drop table IF EXISTS ACT_HI_DETAIL;
drop table IF EXISTS ACT_HI_COMMENT;
drop table IF EXISTS ACT_HI_ATTACHMENT;
